<?xml version="1.0" encoding="utf-8"?><Database Class="BookEntityDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\Library.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="LibraryConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Book" Member="BookEntity">
    <Type Name="BookEntity">
      <Column Name="Author" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Id" AutoSync="Never" Type="System.Int32" DbType="INT" IsReadOnly="true" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
</Database>